[db]
address = "localhost@3306"
username = "root"
password = ""
dbName = "axisChat"
initModel = true

[redis]
address = "localhost@6379;localhost@6380"
passsword = ""
db = 1

[kafka]
address = "localhost:9092"
username = ""
password = ""

[etcd]
address = "localhost:2379"
basePath = "/axis_chat"
serverPathLogic = "logicRpc"
serverPathConnet = "connectRpc"
username = ""
password = ""
connectionTimeout = 5
